name: Build CPython Windows x64 MSI

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'CPython version to build (e.g., 3.11.13, 3.12.5, 3.10.14)'
        required: true
        default: '3.11.13'
        type: string

jobs:
  build-windows-msi:
    runs-on: windows-2022
    timeout-minutes: 120
    
    steps:
    - name: Checkout CPython Source
      uses: actions/checkout@v4
      with:
        repository: python/cpython
        ref: v${{ inputs.python_version }}
        fetch-depth: 1
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup Python for Documentation Build
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Documentation Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install sphinx blurb python-docs-theme
    
    - name: Install WiX Toolset
      run: |
        choco install wixtoolset -y
        echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - name: Download External Dependencies
      run: |
        cd PCbuild
        .\get_externals.bat
      shell: cmd
    
    - name: Build Python Binaries x64
      run: |
        cd PCbuild
        build.bat -p x64 -c Release
      shell: cmd
    
    - name: Build HTML Documentation
      run: |
        cd Doc
        make.bat html
      shell: cmd
    
    - name: Build MSI Installer and Bundle x64
      run: |
        cd Tools\msi
        buildrelease.bat -x64 --build
      shell: cmd
    
    - name: Find and List Installer Files
      if: always()
      run: |
        echo "Searching for installer files (.exe and .msi)..."
        Get-ChildItem -Path . -Filter *.exe -Recurse | ForEach-Object { Write-Host "EXE: $($_.FullName)" }
        Get-ChildItem -Path . -Filter *.msi -Recurse | ForEach-Object { Write-Host "MSI: $($_.FullName)" }
      shell: pwsh
    
    - name: Upload x64 Executable Installer
      uses: actions/upload-artifact@v4
      with:
        name: python-${{ inputs.python_version }}-amd64-installer
        path: |
          PCbuild/amd64/en-us/*.exe
          PCbuild/amd64/en-us/*.msi
        if-no-files-found: error
    
    - name: Upload All Installer Files (Fallback)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: all-installer-files-debug
        path: |
          **/*.msi
          **/*.exe
        if-no-files-found: warn
